export { MailIcon } from './MailIcon'
export { LockIcon } from './LockIcon'
export { EyeIcon } from './EyeIcon'
export { EyeOffIcon } from './EyeOffIcon'
export { PhoneIcon } from './PhoneIcon'
export { UserIcon } from './UserIcon'
export { LocationIcon } from './LocationIcon'